var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/profiles/verify/route.js")
R.c("server/chunks/[root-of-the-server]__c49f4745._.js")
R.c("server/chunks/_aeb44b8a._.js")
R.c("server/chunks/node_modules_dfad4f36._.js")
R.c("server/chunks/node_modules_ae5569c2._.js")
R.c("server/chunks/[root-of-the-server]__f64b3208._.js")
R.c("server/chunks/[root-of-the-server]__6fe577fe._.js")
R.c("server/chunks/node_modules_7b29b765._.js")
R.c("server/chunks/_next-internal_server_app_api_profiles_verify_route_actions_90f94049.js")
R.m(733027)
module.exports=R.m(733027).exports
