// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(protected)/admin/cargos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cargos">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/cargos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/admin/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/config">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/admin/controles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/controles">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/controles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/admin/departamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/departamentos">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/departamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/admin/diagnosticos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/diagnosticos">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/diagnosticos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/admin/medidas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/medidas">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/medidas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/admin/modelos-politicas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modelos-politicas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/modelos-politicas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/admin/modelos-politicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modelos-politicas">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/modelos-politicas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/referencias/lgpd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referencias/lgpd">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/referencias/lgpd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[slug]/aviso-portal-titular/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/aviso-portal-titular">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/aviso-portal-titular/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[slug]/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/cookies">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[slug]/declaracao-seguranca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/declaracao-seguranca">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/declaracao-seguranca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[slug]/politica-privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/politica-privacidade">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/politica-privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/artigo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigo">> = Specific
  const handler = {} as typeof import("../../src/app/artigo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/aceitar-convite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/aceitar-convite">> = Specific
  const handler = {} as typeof import("../../src/app/auth/aceitar-convite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/login">> = Specific
  const handler = {} as typeof import("../../src/app/demo/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../src/app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perfil">> = Specific
  const handler = {} as typeof import("../../src/app/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacidade">> = Specific
  const handler = {} as typeof import("../../src/app/privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/auditoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/auditoria">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/auditoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/contato/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/contato">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/contato/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/incidentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/incidentes">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/incidentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/mapeamento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/mapeamento">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/mapeamento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/pedidos-titulares/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/pedidos-titulares">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/pedidos-titulares/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/portal">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/reportes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/reportes">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/reportes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/ripd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/ripd">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/ripd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/conformidade/ropa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/ropa">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/conformidade/ropa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/diagnostico/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/diagnostico">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/diagnostico/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/diagnostico/relatorio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/diagnostico/relatorio">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/diagnostico/relatorio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/planos-acao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/planos-acao">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/planos-acao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/politicas/[politicaId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/politicas/[politicaId]">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/politicas/[politicaId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/politicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/politicas">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/politicas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/responsabilidades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/responsabilidades">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/responsabilidades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/[id]/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/usuarios">> = Specific
  const handler = {} as typeof import("../../src/app/programas/[id]/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas">> = Specific
  const handler = {} as typeof import("../../src/app/programas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sobre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sobre">> = Specific
  const handler = {} as typeof import("../../src/app/sobre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/cargos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cargos">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/cargos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/controles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/controles">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/controles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/departamentos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/departamentos">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/departamentos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/diagnosticos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diagnosticos">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/diagnosticos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/medidas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/medidas">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/medidas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/politica-modelo/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/politica-modelo/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/politica-modelo/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/politica-modelo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/politica-modelo">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/politica-modelo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/artigo/export-word/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/artigo/export-word">> = Specific
  const handler = {} as typeof import("../../src/app/api/artigo/export-word/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/activities">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit/last-activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/last-activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit/last-activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/log">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cargos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cargos">> = Specific
  const handler = {} as typeof import("../../src/app/api/cargos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/departamentos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departamentos">> = Specific
  const handler = {} as typeof import("../../src/app/api/departamentos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/empresas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/empresas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/empresas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas">> = Specific
  const handler = {} as typeof import("../../src/app/api/empresas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/generate-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/generate-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invites/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invites/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/invites/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invites">> = Specific
  const handler = {} as typeof import("../../src/app/api/invites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invites/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invites/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/invites/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/[slug]/contato/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/[slug]/contato">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/[slug]/contato/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/[slug]/reportar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/[slug]/reportar">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/[slug]/reportar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/avatar">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/privacy-consent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/privacy-consent">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/privacy-consent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/verify">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/governanca-grupos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/governanca-grupos">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/governanca-grupos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/logo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/logo">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/logo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/modulos-resumo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/modulos-resumo">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/modulos-resumo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/papel-lgpd/instituicao/[instId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd/instituicao/[instId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/papel-lgpd/instituicao/[instId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/papel-lgpd/instituicao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd/instituicao">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/papel-lgpd/instituicao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/papel-lgpd/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/papel-lgpd/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/papel-lgpd/vinculo/[vinculoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd/vinculo/[vinculoId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/papel-lgpd/vinculo/[vinculoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/papel-lgpd/vinculo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd/vinculo">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/papel-lgpd/vinculo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/pedidos-titulares/[pedidoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/pedidos-titulares/[pedidoId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/pedidos-titulares/[pedidoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/pedidos-titulares/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/pedidos-titulares">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/pedidos-titulares/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/planos-acao/resumo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/planos-acao/resumo">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/planos-acao/resumo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas">> = Specific
  const handler = {} as typeof import("../../src/app/api/programas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/relatorio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/relatorio">> = Specific
  const handler = {} as typeof import("../../src/app/api/relatorio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/solicitar-dados/[slug]/consultar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/solicitar-dados/[slug]/consultar">> = Specific
  const handler = {} as typeof import("../../src/app/api/solicitar-dados/[slug]/consultar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/solicitar-dados/[slug]/enviar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/solicitar-dados/[slug]/enviar">> = Specific
  const handler = {} as typeof import("../../src/app/api/solicitar-dados/[slug]/enviar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/cadastrar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/cadastrar">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/cadastrar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(protected)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(protected)/referencias/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/referencias">> = Specific
  const handler = {} as typeof import("../../src/app/(protected)/referencias/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/perfil/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/perfil">> = Specific
  const handler = {} as typeof import("../../src/app/perfil/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programas/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/programas">> = Specific
  const handler = {} as typeof import("../../src/app/programas/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
