// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/[slug]/aviso-portal-titular" | "/[slug]/cookies" | "/[slug]/declaracao-seguranca" | "/[slug]/politica-privacidade" | "/admin" | "/admin/cargos" | "/admin/config" | "/admin/controles" | "/admin/departamentos" | "/admin/diagnosticos" | "/admin/medidas" | "/admin/modelos-politicas" | "/admin/modelos-politicas/[id]" | "/artigo" | "/auth/aceitar-convite" | "/dashboard" | "/demo" | "/demo/login" | "/divulgacao" | "/forgot-password" | "/login" | "/offline" | "/perfil" | "/privacidade" | "/programas" | "/programas/[id]" | "/programas/[id]/auditoria" | "/programas/[id]/conformidade" | "/programas/[id]/conformidade/contato" | "/programas/[id]/conformidade/incidentes" | "/programas/[id]/conformidade/mapeamento" | "/programas/[id]/conformidade/pedidos-titulares" | "/programas/[id]/conformidade/portal" | "/programas/[id]/conformidade/reportes" | "/programas/[id]/conformidade/ripd" | "/programas/[id]/conformidade/ropa" | "/programas/[id]/diagnostico" | "/programas/[id]/diagnostico/relatorio" | "/programas/[id]/planos-acao" | "/programas/[id]/politicas" | "/programas/[id]/politicas/[politicaId]" | "/programas/[id]/responsabilidades" | "/programas/[id]/usuarios" | "/referencias/lgpd" | "/register" | "/sobre"
type AppRouteHandlerRoutes = "/api/admin/cargos" | "/api/admin/check" | "/api/admin/controles" | "/api/admin/departamentos" | "/api/admin/diagnosticos" | "/api/admin/medidas" | "/api/admin/politica-modelo" | "/api/admin/politica-modelo/[id]" | "/api/ai/suggest-mapeamentos" | "/api/artigo/export-word" | "/api/audit/activities" | "/api/audit/last-activity" | "/api/audit/log" | "/api/audit/programa-members" | "/api/cargos" | "/api/departamentos" | "/api/empresas" | "/api/empresas/[id]" | "/api/generate-pdf" | "/api/invites" | "/api/invites/accept" | "/api/invites/validate" | "/api/portal/[slug]" | "/api/portal/[slug]/contato" | "/api/portal/[slug]/reportar" | "/api/profiles" | "/api/profiles/avatar" | "/api/profiles/privacy-consent" | "/api/profiles/verify" | "/api/programas" | "/api/programas/[id]" | "/api/programas/[id]/governanca-grupos" | "/api/programas/[id]/logo" | "/api/programas/[id]/modulos-resumo" | "/api/programas/[id]/papel-lgpd" | "/api/programas/[id]/papel-lgpd/instituicao" | "/api/programas/[id]/papel-lgpd/instituicao/[instId]" | "/api/programas/[id]/papel-lgpd/vinculo" | "/api/programas/[id]/papel-lgpd/vinculo/[vinculoId]" | "/api/programas/[id]/pedidos-titulares" | "/api/programas/[id]/pedidos-titulares/[pedidoId]" | "/api/programas/[id]/planos-acao/resumo" | "/api/relatorio" | "/api/solicitar-dados/[slug]/consultar" | "/api/solicitar-dados/[slug]/enviar" | "/api/users" | "/api/users/cadastrar" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard" | "/divulgacao" | "/perfil" | "/programas" | "/referencias"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/[slug]/aviso-portal-titular": { "slug": string; }
  "/[slug]/cookies": { "slug": string; }
  "/[slug]/declaracao-seguranca": { "slug": string; }
  "/[slug]/politica-privacidade": { "slug": string; }
  "/admin": {}
  "/admin/cargos": {}
  "/admin/config": {}
  "/admin/controles": {}
  "/admin/departamentos": {}
  "/admin/diagnosticos": {}
  "/admin/medidas": {}
  "/admin/modelos-politicas": {}
  "/admin/modelos-politicas/[id]": { "id": string; }
  "/api/admin/cargos": {}
  "/api/admin/check": {}
  "/api/admin/controles": {}
  "/api/admin/departamentos": {}
  "/api/admin/diagnosticos": {}
  "/api/admin/medidas": {}
  "/api/admin/politica-modelo": {}
  "/api/admin/politica-modelo/[id]": { "id": string; }
  "/api/ai/suggest-mapeamentos": {}
  "/api/artigo/export-word": {}
  "/api/audit/activities": {}
  "/api/audit/last-activity": {}
  "/api/audit/log": {}
  "/api/audit/programa-members": {}
  "/api/cargos": {}
  "/api/departamentos": {}
  "/api/empresas": {}
  "/api/empresas/[id]": { "id": string; }
  "/api/generate-pdf": {}
  "/api/invites": {}
  "/api/invites/accept": {}
  "/api/invites/validate": {}
  "/api/portal/[slug]": { "slug": string; }
  "/api/portal/[slug]/contato": { "slug": string; }
  "/api/portal/[slug]/reportar": { "slug": string; }
  "/api/profiles": {}
  "/api/profiles/avatar": {}
  "/api/profiles/privacy-consent": {}
  "/api/profiles/verify": {}
  "/api/programas": {}
  "/api/programas/[id]": { "id": string; }
  "/api/programas/[id]/governanca-grupos": { "id": string; }
  "/api/programas/[id]/logo": { "id": string; }
  "/api/programas/[id]/modulos-resumo": { "id": string; }
  "/api/programas/[id]/papel-lgpd": { "id": string; }
  "/api/programas/[id]/papel-lgpd/instituicao": { "id": string; }
  "/api/programas/[id]/papel-lgpd/instituicao/[instId]": { "id": string; "instId": string; }
  "/api/programas/[id]/papel-lgpd/vinculo": { "id": string; }
  "/api/programas/[id]/papel-lgpd/vinculo/[vinculoId]": { "id": string; "vinculoId": string; }
  "/api/programas/[id]/pedidos-titulares": { "id": string; }
  "/api/programas/[id]/pedidos-titulares/[pedidoId]": { "id": string; "pedidoId": string; }
  "/api/programas/[id]/planos-acao/resumo": { "id": string; }
  "/api/relatorio": {}
  "/api/solicitar-dados/[slug]/consultar": { "slug": string; }
  "/api/solicitar-dados/[slug]/enviar": { "slug": string; }
  "/api/users": {}
  "/api/users/cadastrar": {}
  "/artigo": {}
  "/auth/aceitar-convite": {}
  "/auth/callback": {}
  "/dashboard": {}
  "/demo": {}
  "/demo/login": {}
  "/divulgacao": {}
  "/forgot-password": {}
  "/login": {}
  "/offline": {}
  "/perfil": {}
  "/privacidade": {}
  "/programas": {}
  "/programas/[id]": { "id": string; }
  "/programas/[id]/auditoria": { "id": string; }
  "/programas/[id]/conformidade": { "id": string; }
  "/programas/[id]/conformidade/contato": { "id": string; }
  "/programas/[id]/conformidade/incidentes": { "id": string; }
  "/programas/[id]/conformidade/mapeamento": { "id": string; }
  "/programas/[id]/conformidade/pedidos-titulares": { "id": string; }
  "/programas/[id]/conformidade/portal": { "id": string; }
  "/programas/[id]/conformidade/reportes": { "id": string; }
  "/programas/[id]/conformidade/ripd": { "id": string; }
  "/programas/[id]/conformidade/ropa": { "id": string; }
  "/programas/[id]/diagnostico": { "id": string; }
  "/programas/[id]/diagnostico/relatorio": { "id": string; }
  "/programas/[id]/planos-acao": { "id": string; }
  "/programas/[id]/politicas": { "id": string; }
  "/programas/[id]/politicas/[politicaId]": { "id": string; "politicaId": string; }
  "/programas/[id]/responsabilidades": { "id": string; }
  "/programas/[id]/usuarios": { "id": string; }
  "/referencias": {}
  "/referencias/lgpd": {}
  "/register": {}
  "/sobre": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
  "/divulgacao": never
  "/perfil": never
  "/programas": never
  "/referencias": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
