// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../../../../../src/app/(protected)/admin/cargos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cargos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/cargos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/admin/config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/config">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/admin/controles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/controles">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/controles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/admin/departamentos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/departamentos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/departamentos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/admin/diagnosticos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/diagnosticos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/diagnosticos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/admin/medidas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/medidas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/medidas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/admin/modelos-politicas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modelos-politicas/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/modelos-politicas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/admin/modelos-politicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/modelos-politicas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/modelos-politicas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/referencias/aigp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referencias/aigp">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/referencias/aigp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/referencias/lgpd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referencias/lgpd">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/referencias/lgpd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/referencias/ppsi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referencias/ppsi">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/referencias/ppsi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/aviso-do-portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/aviso-do-portal">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/aviso-do-portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/aviso-portal-titular/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/aviso-portal-titular">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/aviso-portal-titular/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/cookies">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/declaracao-de-seguranca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/declaracao-de-seguranca">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/declaracao-de-seguranca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/declaracao-seguranca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/declaracao-seguranca">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/declaracao-seguranca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/politica-de-cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/politica-de-cookies">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/politica-de-cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/politica-de-privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/politica-de-privacidade">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/politica-de-privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/politica-privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/politica-privacidade">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/politica-privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/selo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/selo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/selo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/termo-uso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/termo-uso">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/termo-uso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/termos-de-uso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]/termos-de-uso">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/termos-de-uso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/artigo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/artigo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/artigo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/auditor/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auditor/[token]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/auditor/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/auth/aceitar-convite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/aceitar-convite">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/auth/aceitar-convite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/demo/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/login">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/demo/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/divulgacao/first/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/divulgacao/first">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/divulgacao/first/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/divulgacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/divulgacao">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/divulgacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/divulgacao/slides/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/divulgacao/slides">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/divulgacao/slides/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/linkedin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/linkedin">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/linkedin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perfil">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacidade">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/areas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/areas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/areas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/ativos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/ativos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/ativos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/auditoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/auditoria">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/auditoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/contato/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/contato">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/contato/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/incidentes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/incidentes">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/incidentes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/inventario-ia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/inventario-ia">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/inventario-ia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/mapeamento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/mapeamento">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/mapeamento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/pedidos-titulares/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/pedidos-titulares">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/pedidos-titulares/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/portal">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/reportes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/reportes">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/reportes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/ripd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/ripd">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/ripd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/conformidade/ropa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/conformidade/ropa">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/conformidade/ropa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/cultura/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/cultura">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/cultura/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/diagnostico/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/diagnostico">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/diagnostico/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/diagnostico/relatorio-executivo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/diagnostico/relatorio-executivo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/diagnostico/relatorio-executivo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/diagnostico/relatorio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/diagnostico/relatorio">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/diagnostico/relatorio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/escritorio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/escritorio">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/escritorio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/fornecedores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/fornecedores">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/fornecedores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/governanca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/governanca">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/governanca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/planos-acao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/planos-acao">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/planos-acao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/politicas/[politicaId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/politicas/[politicaId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/politicas/[politicaId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/politicas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/politicas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/politicas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/responsabilidades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/responsabilidades">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/responsabilidades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/riscos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/riscos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/riscos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/tarefas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/tarefas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/tarefas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/[id]/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas/[id]/usuarios">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/[id]/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/sobre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sobre">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/sobre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/pdf/[tipo]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[slug]/pdf/[tipo]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/pdf/[tipo]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/cargos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cargos/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/cargos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/cargos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cargos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/cargos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/check">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/config/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/config/status">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/config/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/controles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/controles/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/controles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/controles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/controles">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/controles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/departamentos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/departamentos/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/departamentos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/departamentos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/departamentos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/departamentos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/diagnosticos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diagnosticos/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/diagnosticos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/diagnosticos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/diagnosticos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/diagnosticos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/medidas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/medidas/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/medidas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/medidas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/medidas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/medidas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/politica-modelo/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/politica-modelo/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/politica-modelo/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/politica-modelo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/politica-modelo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/politica-modelo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/admin/system-admins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system-admins">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/admin/system-admins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/ai/suggest-mapeamentos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/suggest-mapeamentos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/ai/suggest-mapeamentos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/artigo/export-word/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/artigo/export-word">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/artigo/export-word/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/audit/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/activities">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/audit/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/audit/last-activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/last-activity">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/audit/last-activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/audit/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/log">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/audit/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/audit/programa-members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/programa-members">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/audit/programa-members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/auditor/[token]/evidencias/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auditor/[token]/evidencias/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/auditor/[token]/evidencias/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/auditor/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auditor/[token]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/auditor/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/cargos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cargos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/cargos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/dashboard/resumo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/resumo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/dashboard/resumo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/departamentos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departamentos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/departamentos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/empresas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/empresas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/empresas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empresas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/empresas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/generate-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-pdf">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/generate-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/invites/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invites/accept">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/invites/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/invites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invites">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/invites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/invites/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invites/validate">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/invites/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/portal/[slug]/contato/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/[slug]/contato">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/portal/[slug]/contato/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/portal/[slug]/reportar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/[slug]/reportar">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/portal/[slug]/reportar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/portal/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/[slug]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/portal/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/portal/[slug]/selo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/[slug]/selo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/portal/[slug]/selo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/profiles/avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/avatar">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/profiles/avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/profiles/privacy-consent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/privacy-consent">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/profiles/privacy-consent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/profiles/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/verify">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/profiles/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/access/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/access">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/access/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/areas/[areaId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/areas/[areaId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/areas/[areaId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/areas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/areas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/areas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/ativos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/ativos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/ativos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/contato/[contatoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/contato/[contatoId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/contato/[contatoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/cultura/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/cultura">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/cultura/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/decisoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/decisoes">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/decisoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/escopo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/escopo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/escopo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/evidencias/[evidenciaId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/evidencias/[evidenciaId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/evidencias/[evidenciaId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/evidencias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/evidencias">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/evidencias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/fornecedores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/fornecedores">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/fornecedores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/governanca-grupos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/governanca-grupos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/governanca-grupos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/governanca/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/governanca">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/governanca/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/logo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/logo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/logo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/modulos-resumo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/modulos-resumo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/modulos-resumo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/papel-lgpd/instituicao/[instId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd/instituicao/[instId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/papel-lgpd/instituicao/[instId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/papel-lgpd/instituicao/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd/instituicao">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/papel-lgpd/instituicao/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/papel-lgpd/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/papel-lgpd/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/papel-lgpd/vinculo/[vinculoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd/vinculo/[vinculoId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/papel-lgpd/vinculo/[vinculoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/papel-lgpd/vinculo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/papel-lgpd/vinculo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/papel-lgpd/vinculo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/pedidos-titulares/[pedidoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/pedidos-titulares/[pedidoId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/pedidos-titulares/[pedidoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/pedidos-titulares/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/pedidos-titulares">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/pedidos-titulares/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/planos-acao/priorizado/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/planos-acao/priorizado">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/planos-acao/priorizado/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/planos-acao/resumo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/planos-acao/resumo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/planos-acao/resumo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/planos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/planos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/planos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/politicas/sugestoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/politicas/sugestoes">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/politicas/sugestoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/questionarios/[assignmentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/questionarios/[assignmentId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/questionarios/[assignmentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/questionarios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/questionarios">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/questionarios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/relatorio-executivo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/relatorio-executivo">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/relatorio-executivo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/reportes/[reporteId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/reportes/[reporteId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/reportes/[reporteId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/riscos/[riscoId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/riscos/[riscoId]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/riscos/[riscoId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/riscos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/riscos">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/riscos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/[id]/sistemas-ia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas/[id]/sistemas-ia">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/[id]/sistemas-ia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/programas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/programas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/relatorio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/relatorio">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/relatorio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/setup/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/status">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/setup/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/setup/test-connection/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/test-connection">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/setup/test-connection/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/solicitar-dados/[slug]/consultar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/solicitar-dados/[slug]/consultar">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/solicitar-dados/[slug]/consultar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/solicitar-dados/[slug]/enviar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/solicitar-dados/[slug]/enviar">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/solicitar-dados/[slug]/enviar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/users/cadastrar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/cadastrar">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/users/cadastrar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../../../../../src/app/(protected)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/(protected)/referencias/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/referencias">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/(protected)/referencias/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/[slug]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/[slug]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/auditor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auditor">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/auditor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/divulgacao/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/divulgacao">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/divulgacao/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/linkedin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/linkedin">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/linkedin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/perfil/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/perfil">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/perfil/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../../../../../src/app/programas/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/programas">> = Specific
  const handler = {} as typeof import("../../../../../../../../src/app/programas/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
