export const SUPABASE_URL="https://jfyetcjogzbuwcpsiglc.supabase.co";
export const SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmeWV0Y2pvZ3pidXdjcHNpZ2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTk0MjMyNDksImV4cCI6MjAzNDk5OTI0OX0.cwDSSyS6-pp4_e7Pe_LcWMtcOfzHYRa1ksTIorJ__qg"
