export const SUPABASE_URL = "https://bqujcsrfblsnvloibmcm.supabase.co";
export const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdWpjc3JmYmxzbnZsb2libWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzOTAzNDEsImV4cCI6MjA5OTk2NjM0MX0.GxuePg3Y45lq6fQSI4vKhq6FNfxTTQZSbprtjQNC-CE";
