var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/programas/[id]/pedidos-titulares/[pedidoId]/route.js")
R.c("server/chunks/[root-of-the-server]__0c14abb7._.js")
R.c("server/chunks/_aeb44b8a._.js")
R.c("server/chunks/node_modules_dfad4f36._.js")
R.c("server/chunks/node_modules_7b29b765._.js")
R.c("server/chunks/node_modules_ae5569c2._.js")
R.c("server/chunks/[root-of-the-server]__6fe577fe._.js")
R.c("server/chunks/[root-of-the-server]__f64b3208._.js")
R.c("server/chunks/bec2d_app_api_programas_[id]_pedidos-titulares_[pedidoId]_route_actions_f80f1835.js")
R.m(268531)
module.exports=R.m(268531).exports
