var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/programas/[id]/papel-lgpd/instituicao/[instId]/route.js")
R.c("server/chunks/[root-of-the-server]__46ee3240._.js")
R.c("server/chunks/_aeb44b8a._.js")
R.c("server/chunks/node_modules_dfad4f36._.js")
R.c("server/chunks/node_modules_7b29b765._.js")
R.c("server/chunks/node_modules_ae5569c2._.js")
R.c("server/chunks/[root-of-the-server]__6fe577fe._.js")
R.c("server/chunks/[root-of-the-server]__f64b3208._.js")
R.c("server/chunks/bec2d_app_api_programas_[id]_papel-lgpd_instituicao_[instId]_route_actions_357fa94f.js")
R.m(610358)
module.exports=R.m(610358).exports
