import type { ProgramaRiscoRow } from "@/lib/services/dataService";

/** Dados estáticos para vitrine interativa — espelha o módulo real de riscos. */
export const LINKEDIN_DEMO_RISCOS: ProgramaRiscoRow[] = [
  {
    id: 1,
    programa_id: 1,
    titulo: "Planilha de RH compartilhada externamente",
    descricao: "Cópia local com dados de colaboradores fora do ambiente controlado.",
    categoria: "privacidade",
    origem_tipo: "manual",
    origem_id: null,
    probabilidade: "alto",
    impacto: "muito_alto",
    score_inerente: 20,
    score_residual: 12,
    status: "em_tratamento",
    estrategia_mitigacao: "Migrar para repositório corporativo com controle de acesso e DLP.",
    responsavel: "DPO",
    data_revisao: null,
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-03-01T14:00:00Z",
  },
  {
    id: 2,
    programa_id: 1,
    titulo: "Conta admin sem MFA em sistema crítico",
    descricao: "Painel de atendimento com credencial privilegiada sem segundo fator.",
    categoria: "seguranca",
    origem_tipo: "diagnostico",
    origem_id: null,
    probabilidade: "medio",
    impacto: "alto",
    score_inerente: 12,
    score_residual: 6,
    status: "identificado",
    estrategia_mitigacao: "Exigir MFA e revisão trimestral de contas privilegiadas.",
    responsavel: "Gestor SI",
    data_revisao: null,
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-03-01T14:00:00Z",
  },
  {
    id: 3,
    programa_id: 1,
    titulo: "Modelo de IA sem avaliação de viés",
    descricao: "Triagem automatizada de currículos sem registro de risco algorítmico.",
    categoria: "conformidade",
    origem_tipo: "mapeamento",
    origem_id: null,
    probabilidade: "medio",
    impacto: "medio",
    score_inerente: 9,
    score_residual: null,
    status: "identificado",
    estrategia_mitigacao: "Inventariar sistema, documentar finalidade e incluir no plano AIGP.",
    responsavel: "Comitê IA",
    data_revisao: null,
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-03-01T14:00:00Z",
  },
  {
    id: 4,
    programa_id: 1,
    titulo: "Prazo de resposta a titular próximo do limite",
    descricao: "Dois pedidos DSAR abertos com SLA em 3 dias úteis.",
    categoria: "direitos_titulares",
    origem_tipo: "dsar",
    origem_id: null,
    probabilidade: "alto",
    impacto: "medio",
    score_inerente: 12,
    score_residual: null,
    status: "em_tratamento",
    estrategia_mitigacao: "Priorizar fila no portal e designar analista dedicado.",
    responsavel: "Encarregado",
    data_revisao: null,
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-03-01T14:00:00Z",
  },
  {
    id: 5,
    programa_id: 1,
    titulo: "Fornecedor SaaS sem cláusula de subprocessador",
    descricao: "Contrato de CRM em renovação sem DPA atualizado.",
    categoria: "operacional",
    origem_tipo: "fornecedor",
    origem_id: null,
    probabilidade: "baixo",
    impacto: "alto",
    score_inerente: 8,
    score_residual: 4,
    status: "mitigado",
    estrategia_mitigacao: "Aditivo contratual assinado; revisão anual de fornecedores.",
    responsavel: "Jurídico",
    data_revisao: null,
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-03-01T14:00:00Z",
  },
];
