var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/relatorio/route.js")
R.c("server/chunks/[root-of-the-server]__73efc4b2._.js")
R.c("server/chunks/node_modules_ae5569c2._.js")
R.c("server/chunks/node_modules_dfad4f36._.js")
R.c("server/chunks/[root-of-the-server]__f64b3208._.js")
R.c("server/chunks/[root-of-the-server]__6fe577fe._.js")
R.c("server/chunks/node_modules_7b29b765._.js")
R.c("server/chunks/_next-internal_server_app_api_relatorio_route_actions_f0c92fa1.js")
R.m(930803)
module.exports=R.m(930803).exports
